export const GET_LINKCHECKER_REPORT = 'GET_LINKCHECKER_REPORT';
export const GET_LINKCHECKER_REPORT_PENDING = 'GET_LINKCHECKER_REPORT_PENDING';
export const GET_LINKCHECKER_REPORT_SUCCESS = 'GET_LINKCHECKER_REPORT_SUCCESS';
export const GET_LINKCHECKER_REPORT_FAIL = 'GET_LINKCHECKER_REPORT_FAIL';
